CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE SCHEMA IF NOT EXISTS content;
CREATE SCHEMA IF NOT EXISTS learning;
CREATE SCHEMA IF NOT EXISTS curriculum;
CREATE SCHEMA IF NOT EXISTS assessment;
CREATE SCHEMA IF NOT EXISTS battle;
CREATE SCHEMA IF NOT EXISTS ops;
CREATE SCHEMA IF NOT EXISTS iam;
CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS l10n;
CREATE SCHEMA IF NOT EXISTS billing;
CREATE SCHEMA IF NOT EXISTS growth;
CREATE SCHEMA IF NOT EXISTS legal;

CREATE TABLE IF NOT EXISTS l10n.locale (
  code text PRIMARY KEY,
  native_name text NOT NULL,
  english_name text NOT NULL,
  is_enabled boolean NOT NULL DEFAULT true,
  fallback_order smallint NOT NULL DEFAULT 0,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS l10n.translation_key (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namespace text NOT NULL,
  key text NOT NULL,
  description text,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_translation_key_namespace_key
  ON l10n.translation_key(namespace, key);

CREATE TABLE IF NOT EXISTS l10n.translation_value (
  key_id bigint NOT NULL REFERENCES l10n.translation_key(id) ON DELETE CASCADE,
  locale_code text NOT NULL REFERENCES l10n.locale(code) ON DELETE CASCADE,
  value text NOT NULL,
  updated_at timestamptz(6) NOT NULL DEFAULT now(),
  PRIMARY KEY (key_id, locale_code)
);

CREATE TABLE IF NOT EXISTS ops.feature_flag (
  key text PRIMARY KEY,
  description text,
  enabled boolean NOT NULL DEFAULT false,
  kill_switch boolean NOT NULL DEFAULT false,
  scope varchar(64) NOT NULL DEFAULT 'global',
  rules jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_feature_flag_scope_enabled
  ON ops.feature_flag(scope, enabled);

CREATE TABLE IF NOT EXISTS ops.feature_flag_audit (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  flag_key text NOT NULL REFERENCES ops.feature_flag(key) ON DELETE CASCADE,
  actor_id uuid,
  action varchar(80) NOT NULL,
  before jsonb,
  after jsonb,
  reason text,
  created_at timestamptz(6) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_feature_flag_audit_flag_created
  ON ops.feature_flag_audit(flag_key, created_at DESC);

CREATE TABLE IF NOT EXISTS ops.dead_letter_entry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source varchar(120) NOT NULL,
  queue_name varchar(120),
  event_type varchar(120),
  payload jsonb NOT NULL,
  error_code varchar(120),
  error_message text,
  status varchar(32) NOT NULL DEFAULT 'open',
  retry_count integer NOT NULL DEFAULT 0,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  resolved_at timestamptz(6)
);

CREATE INDEX IF NOT EXISTS idx_dead_letter_entry_status_created
  ON ops.dead_letter_entry(status, created_at DESC);

INSERT INTO l10n.locale (code, native_name, english_name, is_enabled, fallback_order)
VALUES
  ('vi', 'Tiếng Việt', 'Vietnamese', true, 0),
  ('ja', '日本語', 'Japanese', true, 1),
  ('en', 'English', 'English', true, 2)
ON CONFLICT (code) DO UPDATE
SET native_name = EXCLUDED.native_name,
    english_name = EXCLUDED.english_name,
    is_enabled = EXCLUDED.is_enabled,
    fallback_order = EXCLUDED.fallback_order,
    updated_at = now();

INSERT INTO ops.feature_flag (key, description, enabled, kill_switch, scope, rules)
VALUES
  ('learning_path_engine', 'Enable learner/admin learning path contracts and UI.', false, false, 'global', '{}'),
  ('reading_assist', 'Enable reusable Japanese reading assist APIs and UI affordances.', true, false, 'global', '{}'),
  ('social_growth', 'Enable social login, referrals, share pages, and postcards.', false, false, 'global', '{}'),
  ('legal_consent', 'Enable policy/consent recording and privacy workflows.', false, false, 'global', '{}'),
  ('notification_delivery', 'Enable email/in-app notification delivery workers.', false, false, 'global', '{}'),
  ('external_media_uploads', 'Enable risky external/user media flows after scan provider is configured.', false, true, 'global', '{}')
ON CONFLICT (key) DO UPDATE
SET description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    kill_switch = EXCLUDED.kill_switch,
    scope = EXCLUDED.scope,
    rules = EXCLUDED.rules,
    updated_at = now();
